### ISSUE TITLE
Missing built js in npm package

### ISSUE THREAD

**Issue by CasperLaiTW** [egomolka/vue-money-format#15]
Hi @egomolka 

Thank you for made package, it's awesome.

and new release in npm, there is not dist folder, no built js in here.

![截圖 2021-09-01 上午9 45 24](https://user-images.githubusercontent.com/5094008/131598375-43cafa95-d22d-4b9e-9f0b-9796085bcd05.png)

**Comment by egomolka** [comment]
Thanks for catching that. I was trying to clean some things up and inadvertently broke the build.
I pushed out a new version.
